"""empty message

Revision ID: 849ddb049053
Revises: 
Create Date: 2018-01-26 13:14:26.460158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849ddb049053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_session')
    # ### end Alembic commands ###
